name: SonarCloud C Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run SonarCloud analysis
        run: |
          sonar-scanner \
            -Dsonar.projectKey=<il_tuo_projectKey> \
            -Dsonar.organization=<la_tua_organizzazione> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.cfamily.build-wrapper-output=bw-output \
            -Dsonar.sources=. \
            -Dsonar.cfamily.llvm.cov.reportPath=coverage.info
